fos_rest:
       param_fetcher_listener: force
       view:
              view_response_listener:  true

       exception:
              exception_controller: 'App\Controller\ExceptionController:showAction'

       format_listener:
              rules:
                     - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ]}
                     - { path: '^/', stop: true }
